# Generated by Django 5.1.7 on 2025-04-04 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorados',
            name='estagio',
            field=models.CharField(choices=[('E1', '10k - 100K'), ('E2', '101k - 500K'), ('E3', '501k - 1KK'), ('E4', '1KK+')], max_length=2),
        ),
        migrations.CreateModel(
            name='DisponibilidaDeDeHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(blank=True, null=True)),
                ('agendado', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
